### ISSUE TITLE
Display Problem

### ISSUE THREAD

**Issue by ZichengLiang** [ZichengLiang/CSU11013-GroupB-Team9#11]
Now we should display every piece of information in a line.
<img width="747" alt="Screenshot 2024-03-13 at 14 51 10" src="https://github.com/ZichengLiang/CSU11013-GroupB-Team9/assets/116967748/07b3b185-447b-42ab-b071-3be1f3b63a45">
we want to show like this⬆️

**Comment by ZichengLiang** [comment]
@Pikacrazy are you happy to solve the problem?

**Comment by Pikacrazy** [comment]
I can try, I'll look into it 👍

**Comment by Pikacrazy** [comment]
Have to make some dinner for my family first

**Comment by Pikacrazy** [comment]
ok done, so it's a display problem. i'll get started now

**Comment by ZichengLiang** [comment]
No problem, have a nice dinner with your family!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ZichengLiang** [comment]
Good luck! It should be quite straightforward!😄

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Pikacrazy** [comment]
wasn't quite so simple, Oliver fixed another part of the code further up and it domino effect fixed it,

**Comment by Pikacrazy** [comment]
i just wanted to ask where to find the png for what the program printed is supposed to look like? so if possible i can take a look at whats next

**Comment by ZichengLiang** [comment]
> wasn't quite so simple, Oliver fixed another part of the code further up and it domino effect fixed it,

Ahhh I see, I'll take a look at it a bit later and come back to you

**Comment by ZichengLiang** [comment]
> i just wanted to ask where to find the png for what the program printed is supposed to look like? so if possible i can take a look at whats next

https://github.com/ZichengLiang/CSU11013-GroupB-Team9/blob/main/ProgramArchitecture.png here it is

**Comment by ZichengLiang** [comment]
> i just wanted to ask where to find the png for what the program printed is supposed to look like? so if possible i can take a look at whats next

If you wish you could open an issue and start work on the Widget and Screen classes😄👍

**Comment by ZichengLiang** [comment]
@Pikacrazy Hi Muireann! I see that you fixed the print function, you can make a pull request so I can merge the changes you made into the main branch to keep our program updated 👍🏻

**Comment by ZichengLiang** [comment]
@Pikacrazy Hi Muireann! I have fixed the multiple pieces issue and commited to the branch just now, you don't have to worry about it now

**Comment by ZichengLiang** [comment]
If you're happy we can make a pull request to merge the changes to the main branch, and close the current working branch now!

**Comment by Pikacrazy** [comment]
sure that works,
There was a multiple pieces issue?? 
oh right the overwrite😅
thank you I was too scared to delete something and accidentally break the project for someone else

**Comment by Pikacrazy** [comment]
i am happy with the changes i made yes 👍

**Comment by ZichengLiang** [comment]
> sure that works, There was a multiple pieces issue?? oh right the overwrite😅 thank you I was too scared to delete something and accidentally break the project for someone else

Don't worry, Oliver is working on another branch, the changes we made won't affect him at all! Do whatever you want.

Oh I mean the program can display multiple pieces of info now, instead of only the carrier code (AA, AS...)

Good job for what you've done so far
