### ISSUE TITLE
PI chart issues

### ISSUE THREAD

**Issue by Pikacrazy** [ZichengLiang/CSU11013-GroupB-Team9#25]
Hi everyone, Muireann here. 
I was working away on the PI chart and I have a few questions,

I noticed the array Pieces in both main and dataset is a string array, in dataset I can see that the different aspects of string are broken up into parts ( Origins, Delays, departuretime, etc.) and are each marked with corresponding 
Pieces[1] / Pieces[2] ....Pieces[x]. 

my question is:
how can I call apon 1 specific dataset eg. departure times
- if I need a full list of departure times would I call apon pieces[13]? 
DataPoints.Pieces[13] and then ++1 to go down the colmn?

Any help on understanding how this works would be greatly appreciated.
thank you for your time.

**Comment by ZichengLiang** [comment]
Hi Muireann, 

When we are loading the csv file, we load each line as an array seperated by commas.

However, when the loading is finished, the line is finally stored as an instance of the object "datapoint", those pieces are turned into attributes (variables) in the instance.

I hope this will help!

**Comment by ZichengLiang** [comment]
Hi Muireann, if you want to get the departure times, you can try this:

```
for(int i = 0; i < datapoints.length; i++){
   println (datapoints[i].depTime); // if you want to get the actual departure time;
  (or: println (datapoints[i].CRSDepTime);) // if you want to get the planned departure time)
 }
```

**Comment by Pikacrazy** [comment]
Thank you Zicheng, that helps a lot 👍

**Comment by ZichengLiang** [comment]
Hi Muireann! I've merged your pull request, really good job!!

Now you may have some rest, get yourself around Query class, then try to load data in your pie chart😃👍🏻

Also ask me or Aryan anytime if you have any problem or you want any new functions within the Query class🔍

**Comment by ZichengLiang** [comment]
@Pikacrazy Hi Muireann!

I have added `cancelledFlights()` and `divertedFlights()` into the Query function, click "fetch origin" on your github desktop and you should be able to see them (and use them~)

To make a query, you have to create an instance of the Query class:
`Query aQuery = new  Query(); `
if you want to get the ArrayList for cancelled flights, use the aQuery like this:
`ArrayList cancelledFlights = aQuery.cancelledFlights();`
if you want to get the total number of cancelled flights, do this:
`int cancelledNumber = cancelledFlights.size();`

**Comment by Pikacrazy** [comment]
Thank you Zicheng! I'll create that now
