### ISSUE TITLE
PieChart Cleanup

### ISSUE THREAD

**Issue by ZichengLiang** [ZichengLiang/CSU11013-GroupB-Team9#58]
Hi Muireann, 

When you're free, could you clean up a little the Pie Chart class by these means:

- remove all the "test" comments which are not neccessary now
- put all attributes into right position (for attributes used across the whole Class, put them to the top above constructors, for attributes only used in a particular method, put them inside that method)
- check which attributes are in use, reduce redundant attributes (I'm not sure if there is any in your class, but usually there will be them eheheheh)

Just do them when you're happy, enjoy your long weekend and happy Easter!

**Comment by Pikacrazy** [comment]
Certainly! I'll take a look
