### ISSUE TITLE
Checkboxes for filter

### ISSUE THREAD

**Issue by dannyelx21** [ZichengLiang/CSU11013-GroupB-Team9#62]
Creating check boxes to filter out bar chart (can be used for any of the other aswell)
![Screenshot 2024-04-02 170128](https://github.com/ZichengLiang/CSU11013-GroupB-Team9/assets/162593250/3e2c9846-f3aa-4958-adcc-219f8326466d)

**Comment by ZichengLiang** [comment]
Now this is solved, good job!
